# production:
#   database: 
#     - influxdb
#   frontend:
#     - chronograf
#     - grafana
#   backend:
#     - nats/nats-streaming
#     - telegraf
#   application:
#     - alyvix

version: "3.5"

services:

  nats:
    image: nats
    #image: nats-streaming
    ports:
      - "4222:4222"
      #- "6222:6222"
      #- "8222:8222"
    networks:
      - prod
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure

  telegraf:
    image: telegraf
    networks:
      - prod
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure
    configs:
      # it doesn't respect -config-directory parameter
      #- source: alyvix.conf
      #  target: /etc/telegraf/telegraf.d/alyvix.conf
      - source: telegraf.conf
        target: /etc/telegraf/telegraf.conf

  influxdb:
    image: influxdb
    ports:
      - "8086:8086"
    networks:
      - prod
    volumes:
      - type: volume
        source: influxdb
        target: /var/lib/influxdb
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure

  chronograf:
    image: chronograf
    ports:
      - "8888:8888"
    networks:
      - prod
    volumes:
      - type: volume
        source: chronograf
        target: /var/lib/chronograf
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure
 
networks:
  prod:

volumes:
  influxdb:
  chronograf:

configs:
  #alyvix.conf:
  #  file: ./alyvix.conf
  telegraf.conf:
    file: ./telegraf.conf
