# tick

version: "3"

services:

  influxdb:
    image: influxdb
    ports:
      - "8086:8086"
    networks:
      - tick
    volumes:
      - influxdb:/var/lib/influxdb
#     - type: volume
#       source: influxdb
#       target: /var/lib/influxdb
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      update_config:
        parallelism: 1
        delay: 1s
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 120s
#    env_file:
    environment:
#      INFLUXDB_
#      INFLUXDB_BIND_ADDRESS=
#      INFLUXDB_HTTP_BIND_ADDRESS=
      INFLUXDB_HTTP_AUTH_ENABLED: 'true'
#      INFLUXDB_HTTP_HTTPS_ENABLED=true
#      INFLUXDB_HTTP_HTTPS_CA_CERTIFICATE="ca.crt"
#      INFLUXDB_HTTP_HTTPS_CERTIFICATE="influxdb.crt"
#      INFLUXDB_HTTP_HTTPS_PRIVATE_KEY="influxdb.key"
#   configs:
#     - source: influxdb.conf
#       target: /etc/influxdb/influxdb.conf

  telegraf:
    image: telegraf
    networks:
      - tick
    volumes:
      - ./local.conf:/etc/telegraf/telegraf.d/local.conf
    deploy:
      mode: global
      update_config:
        parallelism: 1
        delay: 1s
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 120s
#    configs:
#      - source: local.conf
#        target: /etc/telegraf/telegraf.d/local.conf

networks:
  tick:

volumes:
  influxdb:

#configs:
# influxdb.conf:
# file: ./influxdb.conf
#  local.conf:
#    file: ./local.conf
